# Constants and global config for SegDT
APP_TITLE = "SegDT — Volumetric Disease Reconstruction"
APP_SUBTITLE = "Diffusion Transformer-Based 3D Pathology Modelling"
THEME_COLOR_PRIMARY = "#7F77DD"
THEME_COLOR_BG = "#0D0E1A"
THEME_COLOR_SURFACE = "#13152A"
THEME_COLOR_SUCCESS = "#1D9E75"
THEME_COLOR_WARNING = "#BA7517"
MAX_SLICES = 300
MIN_SLICES = 10
DEFAULT_NOISE_LEVEL = 0.3
DEFAULT_DIFFUSION_STEPS = 50
TRANSFORMER_HEADS = 8
EMBED_DIM = 256
FAISS_TOP_K = 5
